import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import RegisterModal from "./components/modals/RegisterModal";
import ToastProvider from "./provider/ToastProvider";
import LoginModal from "./components/modals/LoginModal";
import getCurrentUser from "./actions/getcurrentuser";
import RentModal from "./components/modals/RentModal";
import SearchModal from "./components/modals/SearchModal";
// import Formm from "./components/Form/Formm";
// import Modal from "./components/modals/Modal";

// const inter = Inter({ subsets: ["latin"] });
const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={font.className}>
        {/* <Modal isOpen title={"Login MOdal"} /> */}
        <ToastProvider />
        <LoginModal />
        <RegisterModal />
        <SearchModal/>
        <RentModal />
        <Navbar currentuser={currentUser} />
        {/* <Formm/> */}
        <div className="pb-20 pt-28">{children}</div>
      </body>
    </html>
  );
}
